# Generated by Django 4.0.4 on 2022-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_app', '0003_remove_cliente_name_cliente_nombrecliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombreCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='name',
            field=models.CharField(default='foobar', max_length=20),
        ),
    ]
