# Generated by Django 4.0.4 on 2022-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_app', '0005_remove_cliente_name_cliente_nombrecliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarjeta', models.CharField(max_length=145)),
                ('descripcion', models.CharField(max_length=256)),
                ('interes', models.FloatField(default=0.0)),
            ],
        ),
    ]
