# Generated by Django 4.0.4 on 2022-06-11 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sl_app', '0007_clientetarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombreCliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PF', 'Persona Física'), ('PM', 'Persona Moral')], max_length=2, null=True),
        ),
    ]
